### ISSUE TITLE
Advancements from mods don't work

### ISSUE THREAD

**Issue by axd1x8a** [unilock/YepTwo#2]
When you get advancements from mods, Yep doesn't see and send them to velocity

**Comment by unilock** [comment]
What Minecraft version and mod(s) are you testing with?

**Comment by axd1x8a** [comment]
1.20.1, create and hexcasting

**Comment by unilock** [comment]
Those mods both work fine for me, on both Fabric and Forge.

Are you sure you have the correct version of YepTwo installed for your platform? Do advancements from vanilla Minecraft and death messages work properly?

<img width="451" alt="image" src="https://github.com/unilock/YepTwo/assets/11802133/769580ba-e355-43af-bee2-f8a4281f74a6">
<img width="432" alt="image" src="https://github.com/unilock/YepTwo/assets/11802133/9ecc6d03-f72c-4175-8e70-26cc1b394b53">

**Comment by axd1x8a** [comment]
Try with `create:andesite_alloy` advancement, this one doesn't work for some reason

**Comment by unilock** [comment]
That advancement is set to not be announced to chat, so YepTwo doesn't send a message for it.

https://github.com/Creators-of-Create/Create/blob/d66170c8fed5d02ad46f44fd0e66685be88a3170/src/generated/resources/data/create/advancements/andesite_alloy.json#L16

Maybe that should be changed? I think it would then be appropriate to include a `shouldAnnounceToChat` parameter in the plugin message... hm.
