### ISSUE TITLE
1.21 Neoforge Jar doesn't work on 1.21.1 on Neoforge 21.1.72

### ISSUE THREAD

**Issue by LevyWilson** [unilock/YepTwo#3]
Basically my title. Tried running it on ATM10 1.7. Debug log says it's for an older version of neoforge or forge and won't load.

**Comment by unilock** [comment]
Oops. The mod might work as-is if you just rename `mods.toml` in `META-INF` to `neoforge.mods.toml`. I'll get a proper fix out soon.

**Comment by unilock** [comment]
This should now be fixed with d8b321c9f143a61a9f2b6367742e5263726fa8cc. Check Actions for the latest build.

**Comment by LevyWilson** [comment]
> This should now be fixed with [d8b321c](https://github.com/unilock/YepTwo/commit/d8b321c9f143a61a9f2b6367742e5263726fa8cc). Check Actions for the latest build.

Attempted to load with ATM10 1.11. Server won't start with it. 
[crash-2024-10-29_03.34.13-fml.txt](https://github.com/user-attachments/files/17553233/crash-2024-10-29_03.34.13-fml.txt)

**Comment by unilock** [comment]
I forgot to adjust the variable expansion in `neoforge/build.gradle`...

This build should have it fixed: https://github.com/unilock/YepTwo/actions/runs/11571158144

**Comment by LevyWilson** [comment]
Server loaded, but no one can join without the mod installed.
![image](https://github.com/user-attachments/assets/bb7f6e60-b119-4d0e-937d-59f82f48527b)

**Comment by unilock** [comment]
Should be fully fixed with this build: https://github.com/unilock/YepTwo/actions/runs/12303994649

NeoForge exists to spite me specifically I think
