### ISSUE TITLE
Where plugin version?

### ISSUE THREAD

**Issue by Prince527GitHub** [unilock/YepTwo#5]
On Velocity Discord's modrinth page it mentions that there should be a plugin version of YepTwo but there are only releases for modloaders. I'm I missing something here?

![Screenshot From 2024-12-12 00-11-00](https://github.com/user-attachments/assets/5a7668b9-0fdf-4810-ad6a-7791ac6c53e7)

**Comment by unilock** [comment]
There does not exist a plugin version of YepTwo, as I am not a Bukkit developer. I guess I should, um, fix that.

**Comment by Prince527GitHub** [comment]
Thank you for clarifying

**Comment by elliotnash** [comment]
If anyone's interested, I wrote a very basic paper plugin that interfaces with YepLib: https://github.com/elliotnash/YepPaper. 
@Prince527GitHub

**Comment by unilock** [comment]
@elliotnash Awesome, thank you!! I'll add a link to that in the README.

I also saw you had attempted to add a Paper subproject to the existing Architectury Loom project, which I thought was pretty neat, but I guess it didn't work out.

**Comment by elliotnash** [comment]
Sounds good! 

I did mess around for a bit with architectury but I don’t know enough about build systems to get everything working nicely - i’m sure it’s possible and I may take a look again sometime.
